BEGIN TRANSACTION;
DROP TABLE RC_ROCINANTE;
CREATE TABLE RC_ROCINANTE (NAME TEXT PRIMARY KEY, ROCINANTE_GROUP TEXT, ADDRESS TEXT, MAIL1 TEXT, MAIL2 TEXT, MAIL3 TEXT, BIRTHDAY TEXT, UPDATE_DATE TEXT);
INSERT INTO RC_ROCINANTE(NAME,ROCINANTE_GROUP,ADDRESS,MAIL1,MAIL2,MAIL3,BIRTHDAY,UPDATE_DATE) VALUES("Rocinante","Original",null,null,null,null,"2015/03/27",null);
COMMIT;
